---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-dex-github
  namespace: argocd
spec:
  encryptedData:
    clientId: AgCabURV+YN421DFRAdks6IqljBjlySbboGU+Se7ibwBrO1skzcaGSNhZm7M2tshSFyVtr717awiIvUhpVxjCxyS9/WUVJ86HUTUbmAb0Ol7CdT+xLSL/w1eDmMLdfGfcOoRF1o4nrZ1pbnKNfY7rqG9gyyY+LsnpFI4iVhKWmYjIuEfPrk/YwiUIt+jEuSLM3068OQyiEiK/FrTJbyb0ErBxtPKjn8MlFjTgI8fbFUL1Mi5sZvwadOECJJNYVTzSy8slqbAdIchBtmOKnYWbnJz78rhu88oa8zBlEVVuAnJ7RvHha3UeAdlA0U+8sXQsyUsVQ5glVaLULMkP3XIr0eFNKpMC5VcUozvz7aSBxG/GX6rG7rYCzJilG8drrwSXASrmyA+H5tO4lcjEyuZniaG/JtjskL0ia0FkHm11caaDx55nKP7qVp8Gq14RFBL740nAwoBz1EkyuVokgJNExy75yaS7a3HTBvR9jWTI8385VrOJFUOQGb7bdcViF512XkmWN4OdbSyZx6PAIgAphCxvv5HzDBKSFygT1Q+ruFXWb7B6SH6pPTNu+vdrb2aRYyPYqJjjVUUrG+Wnuy2Tds2dyYzn4hRYXRdMIL5UvuiNaUhT3XfPNWaS3YfoBrxKbVbxooK6j/75bXLZcyUPYgM7GannX3frI/cYlK0FIj37l1N+zHUXVQ1q+l3RzBLb76BYyi4qowN0ia924A7D4ZQ4TmShw==
    clientSecret: AgB9aLD/4zJo7ioUZ1sR0cF8Q1PAm6lEuXcfAchzNaAQefi5yFDWIZeRRNu7iSrZUJH+AHro8aWcNlqQmWimoZTLC14rpV8O9yvnrUd0ROSFyoJk0dDb+Rj8L3/CWoa1p3O5CkG46ISf6VXyH5G4f2CGZSzkBWjJV+LalPe1U/PllXshO6Q+I7axo8IbVEp1dMqQ5R1wPh6n6S4LhMyltwN1zbnFdHaxs0M1XMighYaE4S3ZDCr/b5DIcrPBcuQgw/nc8O+e7e9hxy0aiY49aTxV1Vw0gzGbfzWZ3bAO88FCu9SdMa7HPcovoxOWeV5QVIKSa2K/xQN4SgA1Azx5CInsrdHsDhkk/QVtGxuWXV6aM+vaI30CFXdVhesetVG52hXsBzYcYL0x8EX14V5xdWIprStOKzJ3IOlxWb6YV9TxQDQkHmuIng1JGkkzKDK+VSnrBCGQ+CTFmp56VpAKWqFFX742TIWuhH5Q7+2LYLR6pVTPWGc6Dlj10gkovr/LkAQpbUNDtQfIZejnV+YQguqjI2jBb/mFSXh/qVR405QOIy8PtaHRFqIzoHeS0sXGsmsx3QEwS9HTyuH8P+ZeK7VDDvHt44PekJjhQvHztCZVZqKNSGKTrA9QeI/aOXHDXyVUc1wOIdsUJfT1iw0WrzDvluAfq6q6a99tm903Awd8TqkvUCtyTx+qK+HZ8Mp6J6cfed2INKGOhoff/B7VhiBvjegNpOoNrc9XLd4b2VuKpn5tu5tuMF4/
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-dex-github
      namespace: argocd
