gitops-promoter:
  # Prometheus Operator ServiceMonitor (requires monitoring Application synced first).
  prometheus:
    enable: true

  webhookReceiver:
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: promoter-webhook.gitops-promoter.dev

