---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github-oauth
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    clientId: AgAW//e4iLtSNGoaVOZPP86hENFcJ1aeFzwuBspKFEM/UQ4EXZLygRmi0vcWBF/eS3nYiG48b0Cm/f7WVJGj0yTAX8Mo8I1tD+wO332Ciev57hGyk4ZmrddMmXy4gEMfDo7fxJ4Eod6fOfRtkc6aTerGKxHeg2skqsT+PpP+D7w8qwllfD0DMvXWt9ayZPCQ5OEDqU+kfDfWSeOi7N+RrhNuByiSPqQrrdsGVl6Q7YSIAaXqNQtY5EYRKYkWvGeLP67L5N12ln327XWU10EWFoFjfu3uUKUU/f2e7ll7X1JbjFcWWXIOlSUtE0D3LxoE3cQSXMEroScjtySI5bK3PaJeXwoCXTcBvCFGpgcJRef5anaasWzFKSVfYAT5UAwKipPNd5LdJRdtNmr0ND175UWVz9yZi82txHCQo0uLp4yKPOezegKqjk1wAS07Ls6/RVpmslTkvAuM6e7WPvdTGSKdCDCy40i47Ox5M0zw5KHtMN/Ce6KXZcwc1m9a7wQM0sbG2TBNoa90Yi11WQjQDwcuzMkNGua9OJB/WtbaY9XVmNIPXWkUHq6jVATlcjJlrAtaJdkaqUWtGBh6bRms/gXy2niPVb5HlQnyx0AlK7vOGCqDdNScVFKax5sIMvy6WpZ6dg8Y6DBqnGsmdNlkpkDYBoBsLldPk9r2qM71OEpIt3XldA0N2Sn0sXTd8Ll0/lwcUOtS7ruzov7KSMPkYebk8VclRA==
    clientSecret: AgA1YSS9oycpWKFdfYu0PtomceAG2BW7BcZnnksPTaC8LMsh/oR6eynHh77lASQcrcpCvNo3WbswNcN1u7j5E6AQVwLPC/7lLrgVo6yCVMfP0PKrPrD3XtrqdPXKEbTHFYYvi0nWjPBKcBdQQMpa6ZE76QVwx2MUgqPsXzqifMv04+hvnwwitAQ5x92wx2CLsiVuDvW4cePhrLyxQYe4R0sc+9MsBc17WHht1KIm5IPKdk8Tmybp4PgBhLC0k4xtJraZLR5k+TzncQc5yZnuDUvntL6EYyIGZu7UBRsNMK+SVvXCKcyeu37AhhiWxv9Sy97GeEBTufbk5BOiywBsyh438PgIU2zxBEaXo/K9xlC0a3rkcb3CUwubKyAJ8Q53ACpvIpA7CuzDjVoNiNSAXBQZQaVzHmMQ80nz9dWUh4Wh6Ki/rbLcSV0Rw2GIUQOEXLnQPJbYWQSPAlw1Um9jARkpiA9jmCbEwVa5BsL9L3LhClFXlXcbl57obqSMePpasUZgVdn16RUXGXe5W/Utj2YqMMvmfATXD1v+3VOOM8Jhc3+H3umSHQnRk5JPNZfCLUmnK1MeCqACH65+J5kTbmJJDXOwkRwmr3i0pdj3NzQwHiYB2HV/ekS5HpcBTEZmn9OZTcd068sJ4HNg/8sfY7WUJ5wgJl1u+gBaxLoXKu3DR4UKXWE/PQNrj44t5FYyCmUiNbDtbVMQev8c7dCvp22Iabg7LpruauiIv5X3L5ySdoY/z2T3Vj4n
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: monitoring
      name: grafana-github-oauth
      namespace: monitoring
