---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github-oauth
  namespace: monitoring
spec:
  encryptedData:
    clientId: AgClDl1SM9NM8lBk33CWu71BLezJk5+3srluX802+lT12SlhBl7MnbfLugSwQ3pTVNMhXJkyYaLv9wfaudhmMmy9UrvPtDdRc+F+Exn9Bg1N8BYtnvUGv2x/0cQ3GLvOehF9WjqQmfcAc3eHJhKfduViTH7Drr/Ye6wKsjNi5YvmI7CV+Bgrt4Xth41h+hVcSKQyfcywCS/2hZZkVsutzZmsOIhmAuPzpUcZV34bCdy5TvXiEVxi/vMYDJcItPDbO8spJfh8HhpnvtkNBN38M2+EOJFTBEfU2agxJlbckEEysdCpOTkBS+OZXAQtVeQ4sqAGfvAsG2KptU+kdpKSWUr2ZDHoUWaYrE9606RynmVn3vlzJZyS7d+G+qPyufAdISYyEPWDjHOqSRvhwNwZJjyU1MENp9ooSZqWsSrjU6zktaGtTomj87RIs7720ZKdurpbE6rrrISmYRPVeCkUTC/yMpcbAREgGdUygtgADMs+CLWR4bKzX8rRzmlPKVj41enVf4bbmE+INp1dv145EByvHAR0PAmLaE5dT/+Y9+ID6N466oYtYaiAWSCe8zAb4Kh6QyOBEKh6lGHVGWI/YyShbvFni9ncIC7h+aD/rZBFRKLPAMQuNsUJ/Odi/07Ce6ag1f09u71EPBUkWLOVFWYNnRQXVoYxEqN+SvCnPab/2b5DdyeguxydWGGzAuIOYnXcbV+PIqpbfKc9AhcQjkaYnsTcZA==
    clientSecret: AgCLDgSwhSFPlVzx58yexcXnBbqxmboHwobYVxfJErI6e+PY6QLAvo02xpqulaIbyVZOuVBLBFA+HGVmd9TesXdBj9wRJgeGCbYO7v+3c+MUoXTSu4EXc4flLsbTvc8H+TCkloXailZdHnw+GM3oPpvwmzQ0BnlUlP50/yu8lU27OYLBgCYyLfhksqf7l31NDYrekxlezt6mOVsWusyb3IaIA2hUGuNO2OE7mN8ejLj+dLC+o/rSAWIRU7R2WSs/YqXgXG48229vDe52cyBNhW6hqaFAGBXGpW+L00OK4fJINLfwI8GlUxciwA8U23cMRhDUJfR9Fe10Uv3X6hnFFbx+D8VJ6jyv3cUmlZKEWZ+pKlpDw89zMHL12oInAeXE/ta/yujQd3BWWTgaSoN3wXgolTLdE7FNHurubVspxEtseRCgvfyk8lI+v/Y3CNo1IJGpSpPDxFn6K9ghSBhsmunHlk0jiv6/JGqQWnL9+dCZOjmuM6UPG6UTJB62hE35ROuairMA/dH6d/GJhgigvKI/EgFDs0hDu9720SgdMA9ckpPEsmPd61gXPatEuXirnfTO8IAp6gx7UH/9VWbdxay7/xWLMF987o21R5gGnMjh7yeOCMEC8/CbJihgtB7KgOcOMbwPi7EW+fD8h398I2vTnj4/R9ZgAHdfzd78z4uCu9DhGlT++k551zGqlLmSaaT+MNNfqyMFObeXXvlY1VtMUlfbV30wCBPYtkQPTFLUqRmDDbRH9wpp
  template:
    metadata:
      name: grafana-github-oauth
      namespace: monitoring
