---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github-oauth
  namespace: monitoring
spec:
  encryptedData:
    clientId: AgBzPxhb4iyOhVbw0cqqCxjwz6NMfVQFmKbOkI0Ngs95y9H7k9C4efJeqHTbSYi6SxXr4DqdKZANtkyWLEA1KhekrhYTsNH8j9nm4wfYgqzWakZLg1qey/8d1DRliEDbfDlwPk01ps0XLAqUvfpyTdOpRPHJZmgH9a11Fy9uPTr0cI0r5yramd1E+AarmriJtj3yg1+EK8IBse3uN3vSDA0eY1VF7y2RKjHiXatFB4sJpDAx7JmIeA0VgMVJ4CM44E0UsGzU5g5zFqZ71XtZTUbMpxFn0T1W7E0EBGgvqMsab2h39HiFfCK8yEHm8rqN6CqBmqJTa3JhbEg11d/l9e+bbyazTeEnI2LyzVXm9k4opC7VR7+ZHMla2o9jCE5UP5pRC528JZj9lHDsPkOBjWFg4NC72jEKBE57ZYgZZ76IPPACtGNcQ8fJBaEuw7BxZPV4/BHMmEFeI/QIcgsrPyu0Z31cDIjfjDwkIedYqaNSNa3iz6lcAwJzKsQNhV3VVsUhJdOR1peKYkMC0+9+3xhlvKl9QW+qgMBK9lFV9T4KsZQgDazfJtLUdq0GURgEOzLjhlEyet5J6Y0B49ItVAQNPbuWc6JBy1PqLgHhyPpFZYEgMDzQeSlRtFf+KVD1PlLNS4zqN8C4UyWR2NrTFUEGXlY7gGtS4YLwTJ/qXf0Tq+MEK5J5LzjfJ6fsmNBxibiVRXBoeiGlfehLLcjY4ByhX5McLw==
    clientSecret: AgC+aoUOKAHLbg05/nnirlNgM1c7hEkl/X27rQy2xOQuGK+LzaZ0cSZOI1D8o6TmO5P0wOQREoMFT10gAUDE5Ab73soekDLb9SFCYFNDDuIvXMp08tI09Eq06d27gLQmneUL3dWXSunnNtgDQIFImJ44GdmrYpUH/RU3ZSR08xMKjopnrha/d/S/+R5K9PFieUXSDtUZvek14u/uSgQjdB2P4MrjC2Wx0sx0olw+w2eI/bbJpnekf2X/PvlBYdao8IPmxA/VYdLeyXpypmHDpwDdKXeXJ3i0ntCj+WgB8/u0B0kOgBkV/UPZchbcVNiDbHznbbf6BMC0vr/RI2FiecoPHCtD2vtXM1InON+h+t9PxFQYakcBoWrW5RXgwp5ReDkQaWGV7s/t8PHyAbc4AUP2WzstcIerLA5cXUesnEhET0ZQdkHzfqxMyCO6C3v0t/AU7KCVlkOhFDzyqFSatcnHbxuz+iqz1BAWGwA+uSVKMJK72Vt/nfM20g3OkjsdjV2h38lLzyIiWKGwP8f30JbAWTZUOLDX0jGV66TDorWQPq/0FsdAIRC3mnxQ1q/M4UOs15rnN7w40O2AIFClPjZBqePqaeOr00lzDc2xfLNF0r+3GiOmUomR4EDAJGOXKN4b63WuPPUk5D/kcH7ZYRZ50Mg4JhoKpeWrky3i4LLiBF9Td5CazcsCMIdZuzbMzdDTdCUGkjfxXyetqMdqJolS6jJBMuudPp/1i81hWPgubNtzUMNwk35M
  template:
    metadata:
      name: grafana-github-oauth
      namespace: monitoring
