apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-e2e
  namespace: argocd
  labels:
    app.kubernetes.io/name: guestbook
    guestbook-env: e2e
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sourceHydrator:
    drySource:
      repoURL: https://github.com/crenshaw-dev/gitops-promoter-demo
      targetRevision: HEAD
      path: demo-apps/guestbook
      helm:
        releaseName: guestbook-e2e
        valueFiles:
          - env/e2e/values.yaml
    syncSource:
      targetBranch: env/e2e
      path: hydrated/guestbook-e2e
    hydrateTo:
      targetBranch: env/e2e-next
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-e2e
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
