apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: guestbook-e2e
    app.kubernetes.io/name: guestbook
    helm.sh/chart: guestbook-0.1.0
  name: guestbook-e2e
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/instance: guestbook-e2e
    app.kubernetes.io/name: guestbook
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: guestbook-e2e
    app.kubernetes.io/name: guestbook
    helm.sh/chart: guestbook-0.1.0
  name: guestbook-e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: guestbook-e2e
      app.kubernetes.io/name: guestbook
  template:
    metadata:
      annotations:
        guestbook.demo/gitops-promoter-churn: "2026-04-05T19:30:09Z"
      labels:
        app.kubernetes.io/instance: guestbook-e2e
        app.kubernetes.io/name: guestbook
    spec:
      containers:
        - image: gcr.io/google-samples/gb-frontend:v5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: guestbook
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
